loss: ce
segmentation_model: deeplabv3+
encoder_name: resnet34
encoder_weights: imagenet
learning_rate: 0.001
learning_rate_schedule_patience: 6
verbose: false
in_channels: 4
num_classes: 9
num_filters: 1
ignore_index: 0
