
experiment:
  task: "MarshMapping"
  module:
    arch: "unet" # archs = [Unet, UnetPlusPlus, MAnet, Linknet, FPN, PSPNet, DeepLabV3, DeepLabV3Plus, PAN]
    encoder_name: "resnet34"
    encoder_weights: "imagenet"
    in_channels: 4 # if ndvi or ndwi is true, the input channels should be increased accordingly
    out_classes: 1
  dataloader:
    labelpath: "../../MarshMapping_local/data/NAIP_data_processing/labels_tmi_modified_valid.csv" # "../data/NAIP_data_processing/labels_tmi.csv" / "../data/sentinel_data_processing/labels_tmi.csv"
    data_root_dir: "../../MarshMapping_local/data/NAIP_data_processing/image_patch" # "../data/NAIP_data_processing/image_patch" &  "../data/sentinel_data_processing/image_multiband_128"
    batch_size: 5
    num_workers: 0
    normalization: True
    ndvi: True
    ndwi: False
    datasource: "naip"
    out_dir: "./outputs_binary_tmi_naip"

