
experiment:
  task: "MarshMapping"
  module:
    arch: "unet" # archs = [Unet, UnetPlusPlus, MAnet, Linknet, FPN, PSPNet, DeepLabV3, DeepLabV3Plus, PAN]
    encoder_name: "resnet34"
    encoder_weights: "imagenet"
    in_channels: 4 # if ndvi or ndwi is true, the input channels should be increased accordingly
    out_classes: 1
  dataloader:
    labelpath: "../data/NAIP/NAIP_data_highlow_50000.csv"
    batch_size: 32
    num_workers: 0
    normalization: True
    ndvi: False
    ndwi: False
    datasource: "naip"
    out_dir: "../outputs_binary_sharp"

