experiment:
  task: "SharpClassificiation"
  module:
    loss: "ce"
    segmentation_model: "linknet"
    encoder_name: "resnet34"
    encoder_weights: "imagenet"
    learning_rate: 1e-3
    learning_rate_schedule_patience: 6
    verbose: false
    in_channels: 4
    num_classes: 3
    num_filters: 1 # this is the input for FCN
    ignore_index: 0
  dataloader:
    labelpath: "../data/NAIP/NAIP_data_highlow_50000.csv" #NAIP_data_highlow_512.csv
    batch_size: 32
    num_workers: 0
    normalization: True
    ndvi: False
    ndwi: False
    datasource: "naip"
    out_dir: "../outputs_None"
    tracker_val: "val_loss"
    tracker_mode: "min"