experiment:
  task: "SharpClassificiation"
  module:
    loss: "ce"
    segmentation_model: "linknet"
    encoder_name: "resnet34"
    encoder_weights: "imagenet"
    learning_rate: 1e-3
    learning_rate_schedule_patience: 6
    verbose: false
    in_channels: 4
    num_classes: 3
    num_filters: 1 # this is the input for FCN
    ignore_index: 0
  dataloader:
<<<<<<< HEAD
    labelpath: "../data/NAIP/NAIP_data_highlow_50000_valid.csv" #NAIP_data_highlow_512.csv
    batch_size: 16
=======
    labelpath: "../../MarshMapping_local/data/NAIP/NAIP_data_highlow_50000.csv" #NAIP_data_highlow_512.csv
    batch_size: 32
>>>>>>> a00eda755a52df37f51b0ab56be0654bdd1c7e33
    num_workers: 0
    normalization: True
    ndvi: True
    ndwi: False
    datasource: "naip"
    out_dir: "../outputs/outputs_binary_sharp_naip"
    tracker_val: "val_loss"
    tracker_mode: "min"